[
    {
      "_id": "63ef4eb7476230641c4c0fbc",
      "UID": 606,
      "pid": 937,
      "Genus": "Panicum",
      "Species": "hemitomon",
      "ScientificName": "Panicum hemitomon",
      "CommonName": "maidencane",
      "Category": "Monocot",
      "Family": "Poaceae",
      "FamilySymbol": "POACEA",
      "FamilyCommonName": "Grass family",
      "xOrder": "Cyperales",
      "SubClass": "Commelinidae",
      "Class": "Liliopsida",
      "Division": "Magnoliophyta",
      "SuperDivision": "Spermatophyta",
      "SubKingdom": "Tracheobionta",
      "Kingdom": "Plantae",
      "ITIS_TSN": "40909",
      "Duration": "Perennial",
      "GrowthHabit": "Graminoid",
      "MaxHeight20Yrs": "0",
      "MatureHeight": "0",
      "MinFrostFreeDays": "0",
      "pH_Minimum": "0",
      "pH_Maximum": "0",
      "Min_PlantingDensity": "0",
      "Max_PlantingDensity": "0",
      "Precipitation_Minimum": "0",
      "Precipitation_Maximum": "0",
      "RootDepthMinimum": "0",
      "TemperatureMinimum": "0",
      "Seeds_per_Pound": "0"
    },
    {
      "_id": "63ef4ed4476230641c4c6af0",
      "UID": 23954,
      "pid": 25830,
      "Genus": "Amphicarpum",
      "Species": "NA",
      "ScientificName": "Amphicarpum",
      "CommonName": "maidencane",
      "Category": "Monocot",
      "Family": "Poaceae",
      "FamilySymbol": "POACEA",
      "FamilyCommonName": "Grass family",
      "xOrder": "Cyperales",
      "SubClass": "Commelinidae",
      "Class": "Liliopsida",
      "Division": "Magnoliophyta",
      "SuperDivision": "Spermatophyta",
      "SubKingdom": "Tracheobionta",
      "Kingdom": "Plantae",
      "ITIS_TSN": "41383",
      "MaxHeight20Yrs": "0",
      "MatureHeight": "0",
      "MinFrostFreeDays": "0",
      "pH_Minimum": "0",
      "pH_Maximum": "0",
      "Min_PlantingDensity": "0",
      "Max_PlantingDensity": "0",
      "Precipitation_Minimum": "0",
      "Precipitation_Maximum": "0",
      "RootDepthMinimum": "0",
      "TemperatureMinimum": "0",
      "Seeds_per_Pound": "0"
    },
    {
      "_id": "63ef4ed4476230641c4c6afc",
      "UID": 23966,
      "pid": 25842,
      "Genus": "Amphicarpum",
      "Species": "NA",
      "ScientificName": "Amphicarpum muehlenbergianum",
      "CommonName": "Muhlenberg maidencane",
      "Category": "Monocot",
      "Family": "Poaceae",
      "FamilySymbol": "POACEA",
      "FamilyCommonName": "Grass family",
      "xOrder": "Cyperales",
      "SubClass": "Commelinidae",
      "Class": "Liliopsida",
      "Division": "Magnoliophyta",
      "SuperDivision": "Spermatophyta",
      "SubKingdom": "Tracheobionta",
      "Kingdom": "Plantae",
      "ITIS_TSN": "41386",
      "Duration": "Perennial",
      "GrowthHabit": "Graminoid",
      "MaxHeight20Yrs": "0",
      "MatureHeight": "0",
      "MinFrostFreeDays": "0",
      "pH_Minimum": "0",
      "pH_Maximum": "0",
      "Min_PlantingDensity": "0",
      "Max_PlantingDensity": "0",
      "Precipitation_Minimum": "0",
      "Precipitation_Maximum": "0",
      "RootDepthMinimum": "0",
      "TemperatureMinimum": "0",
      "Seeds_per_Pound": "0"
    },
    {
      "_id": "63ef4ed4476230641c4c6b08",
      "UID": 23978,
      "pid": 25854,
      "Genus": "Amphicarpum",
      "Species": "NA",
      "ScientificName": "Amphicarpum purshii",
      "CommonName": "blue maidencane",
      "Category": "Monocot",
      "Family": "Poaceae",
      "FamilySymbol": "POACEA",
      "FamilyCommonName": "Grass family",
      "xOrder": "Cyperales",
      "SubClass": "Commelinidae",
      "Class": "Liliopsida",
      "Division": "Magnoliophyta",
      "SuperDivision": "Spermatophyta",
      "SubKingdom": "Tracheobionta",
      "Kingdom": "Plantae",
      "ITIS_TSN": "41387",
      "Duration": "Annual, Perennial",
      "GrowthHabit": "Graminoid",
      "MaxHeight20Yrs": "0",
      "MatureHeight": "0",
      "MinFrostFreeDays": "0",
      "pH_Minimum": "0",
      "pH_Maximum": "0",
      "Min_PlantingDensity": "0",
      "Max_PlantingDensity": "0",
      "Precipitation_Minimum": "0",
      "Precipitation_Maximum": "0",
      "RootDepthMinimum": "0",
      "TemperatureMinimum": "0",
      "Seeds_per_Pound": "0"
    }
  ]